#!/bin/bash
#  /etc/init.d/pocsag

### BEGIN INIT INFO
# Provides: pocsag scanning and decoding features
# Required-Start: 
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: scans a pocsag frequency and decode the content
# Description: --
### END INIT INFO

# Some things that run always
#touch /var/lock/pocsag

source pocsag.conf

function store1
{
	if [[ "$@" == *Alpha:* ]] ; then
		filename1=`date +%d-%m-%Y`@"$pocsag_freq1"Hz.txt
		echo "$@" >> $pocsag_save_path$filename1
	fi
}

function store2
{
        if [[ "$@" == *Alpha:* ]] ; then
                filename2=`date +%d-%m-%Y`@"$pocsag_freq2"Hz.txt
                echo "$@" >> $pocsag_save_path$filename2
        fi
}

case "$1" in
 'start')
	rmmod dvb_usb_rtl28xxu

	rtl_fm -f $pocsag_freq1 -M fm -s 22050 -g 30 -E dc -F 0 -d 0| multimon-ng -t raw -a POCSAG512 -a POCSAG1200 -a POCSAG2400 -f alpha -p -b1 /dev/stdin | { while read line; do store1 "$line"; done } &
	rtl_fm -f $pocsag_freq2 -M fm -s 22050 -g 30 -E dc -F 0 -d 1| multimon-ng -t raw -a POCSAG512 -a POCSAG1200 -a POCSAG2400 -f alpha -p -b1 /dev/stdin | { while read line; do store2 "$line"; done } &

  	echo "$(tput setaf 6)pocsag monitoring started$(tput sgr 0)";; 
 'stop')
   	echo "$(tput setaf 6)Shutdown pocsag monitoring$(tput sgr 0)"
   	ps aux | grep -ie pocsag | awk '{print $2}' | xargs kill -9
   	ps aux | grep -ie rtl_fm | awk '{print $2}' | xargs kill -9
   	ps aux | grep -ie multimon-ng | awk '{print $2}' | xargs kill -9
	;;
  *)
	echo "Usage: /etc/init.d/pocsag {start|stop}"
	exit 1
    	;;

esac
